name: cse517_final_project
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3.0
  - torchmetrics=0.11.4
  - transformers=4.30.2
  - pip:
      - torchvision==0.15.1+cu117
      - torchaudio==2.0.1+cu117
      - torch-geometric==2.3.0
      - torch-cluster==1.6.1+pt20cu117
      - torch-scatter==2.1.1+pt20cu117
      - torch-sparse==0.6.17+pt20cu117
      - torch-spline-conv==1.2.2+pt20cu117